# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from ...utils import serialize_int, validate_int
import pydantic
from pydantic import model_serializer
from pydantic.functional_serializers import PlainSerializer
from pydantic.functional_validators import BeforeValidator
from typing import Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class CompositeMediaBlobstore2InfoTypedDict(TypedDict):
    r"""Blobstore v2 info, set if reference_type is BLOBSTORE_REF and it refers
    to a v2 blob.
    """

    blob_generation: NotRequired[int]
    r"""The blob generation id."""
    blob_id: NotRequired[str]
    r"""The blob id, e.g., /blobstore/prod/playground/scotty"""
    download_external_read_token: NotRequired[str]
    r"""A serialized External Read Token passed from Bigstore -> Scotty for a GCS
    download. This field must never be consumed outside of Bigstore, and is not
    applicable to non-GCS media uploads.
    """
    download_read_handle: NotRequired[str]
    r"""Read handle passed from Bigstore -> Scotty for a GCS download.
    This is a signed, serialized blobstore2.ReadHandle proto which must never
    be set outside of Bigstore, and is not applicable to non-GCS media
    downloads.
    """
    read_token: NotRequired[str]
    r"""The blob read token. Needed to read blobs that have not been
    replicated. Might not be available until the final call.
    """
    upload_fragment_list_creation_info: NotRequired[str]
    r"""A serialized Object Fragment List Creation Info passed from Bigstore ->
    Scotty for a GCS upload. This field must never be consumed outside of
    Bigstore, and is not applicable to non-GCS media uploads.
    """
    upload_metadata_container: NotRequired[str]
    r"""Metadata passed from Blobstore -> Scotty for a new GCS upload.
    This is a signed, serialized blobstore2.BlobMetadataContainer proto which
    must never be consumed outside of Bigstore, and is not applicable to
    non-GCS media uploads.
    """


class CompositeMediaBlobstore2Info(BaseModel):
    r"""Blobstore v2 info, set if reference_type is BLOBSTORE_REF and it refers
    to a v2 blob.
    """

    blob_generation: Annotated[
        Optional[int],
        BeforeValidator(validate_int),
        PlainSerializer(serialize_int(True)),
    ] = None
    r"""The blob generation id."""

    blob_id: Optional[str] = None
    r"""The blob id, e.g., /blobstore/prod/playground/scotty"""

    download_external_read_token: Optional[str] = None
    r"""A serialized External Read Token passed from Bigstore -> Scotty for a GCS
    download. This field must never be consumed outside of Bigstore, and is not
    applicable to non-GCS media uploads.
    """

    download_read_handle: Optional[str] = None
    r"""Read handle passed from Bigstore -> Scotty for a GCS download.
    This is a signed, serialized blobstore2.ReadHandle proto which must never
    be set outside of Bigstore, and is not applicable to non-GCS media
    downloads.
    """

    read_token: Optional[str] = None
    r"""The blob read token. Needed to read blobs that have not been
    replicated. Might not be available until the final call.
    """

    upload_fragment_list_creation_info: Optional[str] = None
    r"""A serialized Object Fragment List Creation Info passed from Bigstore ->
    Scotty for a GCS upload. This field must never be consumed outside of
    Bigstore, and is not applicable to non-GCS media uploads.
    """

    upload_metadata_container: Optional[str] = None
    r"""Metadata passed from Blobstore -> Scotty for a new GCS upload.
    This is a signed, serialized blobstore2.BlobMetadataContainer proto which
    must never be consumed outside of Bigstore, and is not applicable to
    non-GCS media uploads.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "blob_generation",
                "blob_id",
                "download_external_read_token",
                "download_read_handle",
                "read_token",
                "upload_fragment_list_creation_info",
                "upload_metadata_container",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CompositeMediaObjectIDTypedDict(TypedDict):
    r"""Reference to a TI Blob, set if reference_type is BIGSTORE_REF."""

    bucket_name: NotRequired[str]
    r"""The name of the bucket to which this object belongs."""
    generation: NotRequired[int]
    r"""Generation of the object. Generations are monotonically increasing
    across writes, allowing them to be be compared to determine which
    generation is newer. If this is omitted in a request, then you are
    requesting the live object.
    See http://go/bigstore-versions
    """
    object_name: NotRequired[str]
    r"""The name of the object."""


class CompositeMediaObjectID(BaseModel):
    r"""Reference to a TI Blob, set if reference_type is BIGSTORE_REF."""

    bucket_name: Optional[str] = None
    r"""The name of the bucket to which this object belongs."""

    generation: Annotated[
        Optional[int],
        BeforeValidator(validate_int),
        PlainSerializer(serialize_int(True)),
    ] = None
    r"""Generation of the object. Generations are monotonically increasing
    across writes, allowing them to be be compared to determine which
    generation is newer. If this is omitted in a request, then you are
    requesting the live object.
    See http://go/bigstore-versions
    """

    object_name: Optional[str] = None
    r"""The name of the object."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["bucket_name", "generation", "object_name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


CompositeMediaReferenceType = Union[
    Literal[
        "path",
        "blob_ref",
        "inline",
        "bigstore_ref",
        "cosmo_binary_reference",
    ],
    UnrecognizedStr,
]
r"""Describes what the field reference contains."""


class CompositeMediaTypedDict(TypedDict):
    r"""A sequence of media data references representing composite data.
    Introduced to support Bigstore composite objects. For details, visit
    http://go/bigstore-composites.
    """

    blob_ref: NotRequired[str]
    r"""Blobstore v1 reference, set if reference_type is BLOBSTORE_REF
    This should be the byte representation of a blobstore.BlobRef.
    Since Blobstore is deprecating v1, use blobstore2_info instead.
    For now, any v2 blob will also be represented in this field as
    v1 BlobRef.
    """
    blobstore2_info: NotRequired[CompositeMediaBlobstore2InfoTypedDict]
    r"""Blobstore v2 info, set if reference_type is BLOBSTORE_REF and it refers
    to a v2 blob.
    """
    cosmo_binary_reference: NotRequired[str]
    r"""A binary data reference for a media download. Serves as a
    technology-agnostic binary reference in some Google infrastructure.
    This value is a serialized storage_cosmo.BinaryReference proto. Storing
    it as bytes is a hack to get around the fact that the cosmo proto
    (as well as others it includes) doesn't support JavaScript. This
    prevents us from including the actual type of this field.
    """
    crc32c_hash: NotRequired[int]
    r"""crc32.c hash for the payload."""
    inline: NotRequired[str]
    r"""Media data, set if reference_type is INLINE"""
    length: NotRequired[int]
    r"""Size of the data, in bytes"""
    md5_hash: NotRequired[str]
    r"""MD5 hash for the payload."""
    object_id: NotRequired[CompositeMediaObjectIDTypedDict]
    r"""Reference to a TI Blob, set if reference_type is BIGSTORE_REF."""
    path: NotRequired[str]
    r"""Path to the data, set if reference_type is PATH"""
    reference_type: NotRequired[CompositeMediaReferenceType]
    r"""Describes what the field reference contains."""
    sha1_hash: NotRequired[str]
    r"""SHA-1 hash for the payload."""


class CompositeMedia(BaseModel):
    r"""A sequence of media data references representing composite data.
    Introduced to support Bigstore composite objects. For details, visit
    http://go/bigstore-composites.
    """

    blob_ref: Annotated[
        Optional[str],
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible."
        ),
    ] = None
    r"""Blobstore v1 reference, set if reference_type is BLOBSTORE_REF
    This should be the byte representation of a blobstore.BlobRef.
    Since Blobstore is deprecating v1, use blobstore2_info instead.
    For now, any v2 blob will also be represented in this field as
    v1 BlobRef.
    """

    blobstore2_info: Optional[CompositeMediaBlobstore2Info] = None
    r"""Blobstore v2 info, set if reference_type is BLOBSTORE_REF and it refers
    to a v2 blob.
    """

    cosmo_binary_reference: Optional[str] = None
    r"""A binary data reference for a media download. Serves as a
    technology-agnostic binary reference in some Google infrastructure.
    This value is a serialized storage_cosmo.BinaryReference proto. Storing
    it as bytes is a hack to get around the fact that the cosmo proto
    (as well as others it includes) doesn't support JavaScript. This
    prevents us from including the actual type of this field.
    """

    crc32c_hash: Optional[int] = None
    r"""crc32.c hash for the payload."""

    inline: Optional[str] = None
    r"""Media data, set if reference_type is INLINE"""

    length: Annotated[
        Optional[int],
        BeforeValidator(validate_int),
        PlainSerializer(serialize_int(True)),
    ] = None
    r"""Size of the data, in bytes"""

    md5_hash: Optional[str] = None
    r"""MD5 hash for the payload."""

    object_id: Optional[CompositeMediaObjectID] = None
    r"""Reference to a TI Blob, set if reference_type is BIGSTORE_REF."""

    path: Optional[str] = None
    r"""Path to the data, set if reference_type is PATH"""

    reference_type: Optional[CompositeMediaReferenceType] = None
    r"""Describes what the field reference contains."""

    sha1_hash: Optional[str] = None
    r"""SHA-1 hash for the payload."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "blob_ref",
                "blobstore2_info",
                "cosmo_binary_reference",
                "crc32c_hash",
                "inline",
                "length",
                "md5_hash",
                "object_id",
                "path",
                "reference_type",
                "sha1_hash",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
