# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from ...utils import serialize_int, validate_int
from pydantic import model_serializer
from pydantic.functional_serializers import PlainSerializer
from pydantic.functional_validators import BeforeValidator
from typing import Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


EnvironmentFileType = Union[
    Literal[
        "file",
        "directory",
    ],
    UnrecognizedStr,
]
r"""Output only. The type of the entry."""


class EnvironmentFileTypedDict(TypedDict):
    r"""Metadata for a file or directory within an environment."""

    mime_type: NotRequired[str]
    r"""Output only. The MIME type of the file (e.g., \"text/python\", \"image/png\").
    Empty for directories.
    """
    name: NotRequired[str]
    r"""Output only. The name of the file or directory (e.g., \"main.py\" or \"src\")."""
    path: NotRequired[str]
    r"""Output only. The full relative path within the environment
    (e.g., \"workspace/src/main.py\").
    """
    size_bytes: NotRequired[int]
    r"""Output only. The size of the file/directory in bytes."""
    type: NotRequired[EnvironmentFileType]
    r"""Output only. The type of the entry."""


class EnvironmentFile(BaseModel):
    r"""Metadata for a file or directory within an environment."""

    mime_type: Optional[str] = None
    r"""Output only. The MIME type of the file (e.g., \"text/python\", \"image/png\").
    Empty for directories.
    """

    name: Optional[str] = None
    r"""Output only. The name of the file or directory (e.g., \"main.py\" or \"src\")."""

    path: Optional[str] = None
    r"""Output only. The full relative path within the environment
    (e.g., \"workspace/src/main.py\").
    """

    size_bytes: Annotated[
        Optional[int],
        BeforeValidator(validate_int),
        PlainSerializer(serialize_int(True)),
    ] = None
    r"""Output only. The size of the file/directory in bytes."""

    type: Optional[EnvironmentFileType] = None
    r"""Output only. The type of the entry."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["mime_type", "name", "path", "size_bytes", "type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
